language: node_js
node_js:
  - "6.9.1"
install:
  - npm install yarn -g
  - yarn
script:
  - npm run test && npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
cache:
  directories:
    - node_modules
