language: node_js
node_js:
  - "7.8.0"
script:
  - npm run test && npm run build
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: true
cache:
  yarn: true
  directories:
    - node_modules
after_success: npm run codecov
